name: Eleventy Build

on:
  push:
    branches:
      - "simplified-layout"

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Install npm packages
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          PUBLISH_DIR: _site
          PUBLISH_BRANCH: gh-pages
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
